# Image Manipulations
## This notebook outlines the different techniques used on images using OpenCV library

**Image Manipulations**
- Cropping an image
- Flipping an image
- Masking an image

### Import the necessary libraries

In [1]:
from __future__ import print_function
import argparse
import cv2
import numpy as np

### Load an image
#### imread( )

In [5]:
image = cv2.imread("image.jpg")

In [6]:
image

array([[[139, 154, 173],
        [142, 157, 176],
        [142, 157, 176],
        ...,
        [158, 179, 200],
        [156, 177, 198],
        [154, 175, 196]],

       [[135, 150, 169],
        [139, 154, 173],
        [139, 154, 173],
        ...,
        [158, 179, 200],
        [157, 178, 199],
        [156, 177, 198]],

       [[136, 151, 170],
        [142, 157, 176],
        [141, 156, 175],
        ...,
        [158, 179, 200],
        [159, 180, 201],
        [160, 181, 202]],

       ...,

       [[133, 147, 169],
        [132, 146, 168],
        [129, 146, 167],
        ...,
        [134, 152, 175],
        [133, 151, 174],
        [133, 151, 174]],

       [[132, 146, 168],
        [131, 145, 167],
        [128, 145, 166],
        ...,
        [135, 153, 176],
        [135, 153, 176],
        [134, 152, 175]],

       [[132, 146, 168],
        [131, 145, 167],
        [128, 145, 166],
        ...,
        [133, 151, 174],
        [133, 151, 174],
        [130, 148, 171]]

### Load your favorite image and display it


In [8]:
image = cv2.imread("image.jpg")
cv2.imshow("Original", image)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

# Cropping an image

Cropping removes the outer parts of the image that we are not interested in.

Cropping an image is as simple as using **array slices** in NumPy! 

Let's crop out the **face of the T-Rex**. 


We are supplying NumPy array slices to extract a rectangular region of the image, starting at (240, 30) and ending at (335,120). The order in which we supply the indexes to the crop may seem counterintuitive; however, remember that OpenCV represents images as NumPy arrays with the the height first and the width second. This means that we need to supply our y-axis values before our x-axis.

The order in which we specify the coordinates is:
- startY:endY
- startX:endX

In this case, we are 
- starting at Y=?? and ending at Y=??
- start at X=?? and end at X=??

In [5]:
cropped = image[30:120 , 240:335]
cv2.imshow("T-Rex Face", cropped)
cv2.waitKey(0)

13

# Flipping an image
- Horizontal
- Vertical
- Both Axes

The **cv2.flip method** requires two arguments
- the **image** we want to flip
- **flip code** that is used to determine how we are going to flip the image
    - 1 --> horizontal flipping (y-axis)
    - 0 --> vertical (x-axis)
    - -1 --> both axes

### Flip the image horizontally

In [6]:
flipped = cv2.flip(image, 1)
cv2.imshow("Flipped Horizontally", flipped)
cv2.waitKey(0)

13

### Flip the image vertically

In [7]:
flipped = cv2.flip(image, 0)
cv2.imshow("Flipped Vertically", flipped)
cv2.waitKey(0)

13

### Flip the image along both axes

In [8]:
flipped = cv2.flip(image, -1)
cv2.imshow("Flipped Horizontally & Vertically", flipped)
cv2.waitKey(0)

13

# Masking an image
Using a mask allows us to focus only on the portions of the image that **interests** us

For example, let’s say that we were building a computer vision system to recognize faces. The only part of the image we are interested in finding and describing are the parts of the image that contain **faces** – we simply don’t care about the rest of the content of the image. 

Assuming that we could find the faces in the image, we might construct a mask to show only the faces in the image and not the unwanted rest of the parts of the image


A mask is the same size as our image, but has only two pixel values, 0 and 255
- Mask Pixels with a value of **0** are **ignored** in the orignal image
- Mask Pixels with a value of **255** are **allowed** to be kept

For example, let's construct a mask with a **150x150 square** at the center of it and mask our image

#### Steps
- Construct a NumPy array filled with **zeros** as same as the input image
- Draw a **rectangle**
- Apply **bitwise_and**
- Display the mask applied to image

#### Construct a Zeros NumPy array with the same size of the input image

In [36]:
mask = np.zeros(image.shape[:2], dtype = "uint8")
mask

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

### Find center

In [27]:
(cX, cY) = (image.shape[1] // 2, image.shape[0] // 2)
(cX, cY)

(480, 640)

### Draw rectangle

In [37]:
cv2.rectangle(mask, (cX - 75, cY - 75), (cX + 75 , cY + 75), 255, -1)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [43]:
print(mask[0,0])
print(mask[cY, cX])

640 480
0
255


### Display the mask

In [38]:
cv2.imshow("NewMask", mask)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

#### Apply the bitwise_and
- image
- image
- mask

By supplying a mask, the cv2.bitwise_and function only examines pixels that are **“on”** in the mask. In this case, only pixels that are part of the white rectangle and omits all others

In [31]:
masked = cv2.bitwise_and(image, image, mask=mask)

### Display the masked image

In [32]:
cv2.imshow("Mask Applied to Image", masked)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

### Extract just the face of the T-rex using your custom mask

In [18]:
mask = np.zeros(image.shape[:2], dtype = "uint8")
cv2.rectangle(mask, (225, 25), (325 , 125), 255, -1)
masked = cv2.bitwise_and(image, image, mask = mask)
cv2.imshow("Mask Applied to Image", masked)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

### Apply a circular mask instead of a rectangular mask

In [41]:
mask = np.zeros(image.shape[:2], dtype = "uint8")
cv2.circle(mask, (cX, cY), 100, 255, -1)
masked = cv2.bitwise_and(image, image, mask = mask)
cv2.imshow("Mask", mask)
cv2.imshow("Mask Applied to Image", masked)
cv2.waitKey(0)

13

### Homework: Take an 007 Bond image and do a circular mask around him just for fun
- Load the image
- Display the image
- Note the coordinates for correct positioning
- Create a Circular Mask with the coordinates
- Apply the mask
- Display the masked image